version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9.8-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_USE_LONGNAME: "true"
    volumes:
      #https://www.rabbitmq.com/configure.html#configuration-files
      - ./rabbitmq:/etc/rabbitmq
      - rabbitmq-data:/var/lib/rabbitmq
volumes:
  rabbitmq-data:

