spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: us
    password: pw
    listener:
      simple:
        retry:
          enabled: true
      direct:
        retry:
          enabled: true

